const params = new URLSearchParams(location.search);
const syncUrl = params.get("sync_url") || "";
const syncRequested =
  params.get("arena_sync") === "1" && allowedSyncUrl(syncUrl);
let recordedRows = [];
if (!syncRequested) {
  const response = await fetch("./metrics.json");
  if (!response.ok) throw new Error("Recorded metrics could not be loaded.");
  recordedRows = await response.json();
}
const fields = {
  reward: { color: "#77a0ff" },
  loss: { color: "#66d59c" },
  kl: { color: "#e7bd5d" },
  mean_length: { color: "#e8758c" },
};
const elements = {
  step: document.getElementById("step"),
  reward: document.getElementById("reward"),
  loss: document.getElementById("loss"),
  kl: document.getElementById("kl"),
  length: document.getElementById("length"),
  play: document.getElementById("play"),
  restart: document.getElementById("restart"),
  position: document.getElementById("position"),
  speed: document.getElementById("speed"),
  state: document.getElementById("run-state"),
};
let rows = recordedRows;
let cursor = 0;
let mode = syncRequested ? "waiting" : "recorded";
let live = null;
let playing =
  mode === "recorded" &&
  !matchMedia("(prefers-reduced-motion: reduce)").matches;
let lastFrame = performance.now();
let accumulator = 0;

function text(id, value) {
  document.getElementById(id).textContent = value;
}

function format(value, digits = 3) {
  if (!Number.isFinite(Number(value))) return "—";
  return Number(value).toLocaleString("en-US", {
    minimumFractionDigits: digits,
    maximumFractionDigits: digits,
  });
}

function labels() {
  const isLive = mode === "live";
  document.body.classList.toggle("live-sync", isLive || mode === "waiting");
  text(
    "eyebrow",
    isLive
      ? `LIVE ARENA SYNC · SEED ${live.seed} · ${live.policy.toUpperCase()}`
      : mode === "waiting"
        ? "WORKER · WAITING FOR ARENA"
        : "WORKER · QWEN2.5-1.5B · GRPO",
  );
  text(
    "headline",
    isLive
      ? "Worker telemetry, synchronized with the Arena."
      : mode === "waiting"
        ? "Open an episode in Sentry Loop."
        : "Watch the learning signal unfold.",
  );
  text(
    "description",
    isLive
      ? "The Arena replay cursor controls this page. Every Worker tool call, measured reward, success result, and Auditor flag below comes from the episode currently playing in the Arena."
      : mode === "waiting"
        ? "This window is connected to its opener and will follow the next Arena replay action."
        : "A timed replay of 216 measurements from the original training run. No model is training now and no values are generated by this page.",
  );
  const values = isLive
    ? {
        "step-label": "ARENA ACTION",
        "step-caption": "shared replay cursor",
        "reward-label": "WORKER REWARD",
        "reward-caption": "cumulative through cursor",
        "loss-label": "ACTION REWARD",
        "loss-caption": "current agent action",
        "kl-label": "SUCCESS RATE",
        "kl-caption": "completed Worker calls",
        "length-label": "AUDITOR FLAGS",
        "length-caption": "raised through cursor",
        "chart-reward-title": "Cumulative Worker reward",
        "chart-reward-caption": "Measured episode signal",
        "chart-loss-title": "Worker action reward",
        "chart-loss-caption": "Reward at each tool call",
        "chart-kl-title": "Tool success rate",
        "chart-kl-caption": "Cumulative percent",
        "chart-length-title": "Auditor flags",
        "chart-length-caption": "Cumulative review signal",
        "footer-state": "LIVE ARENA EPISODE · SYNCHRONIZED REPLAY CURSOR · READ-ONLY TELEMETRY",
      }
    : {
        "step-label": "STEP",
        "step-caption": "optimizer update",
        "reward-label": "REWARD",
        "reward-caption": "group mean",
        "loss-label": "LOSS",
        "loss-caption": "optimization signal",
        "kl-label": "KL",
        "kl-caption": "policy divergence",
        "length-label": "MEAN LENGTH",
        "length-caption": "output tokens",
        "chart-reward-title": "Total reward",
        "chart-reward-caption": "Higher is better",
        "chart-loss-title": "Training loss",
        "chart-loss-caption": "Optimizer output",
        "chart-kl-title": "KL divergence",
        "chart-kl-caption": "Distance from reference",
        "chart-length-title": "Completion length",
        "chart-length-caption": "Mean generated tokens",
        "footer-state": "RECORDED METRIC REPLAY · EXACT SOURCE VALUES · NO SMOOTHING",
      };
  for (const [id, value] of Object.entries(values)) text(id, value);
  for (const control of [
    elements.play,
    elements.restart,
    elements.position,
    elements.speed,
  ])
    control.disabled = mode !== "recorded";
  document.title = isLive
    ? "Live Arena Worker · Sentry Loop"
    : "Sentry Loop · Live metric replay";
}

function chart(canvas, key) {
  const ratio = devicePixelRatio || 1;
  const width = canvas.clientWidth;
  const height = canvas.clientHeight;
  if (
    canvas.width !== Math.round(width * ratio) ||
    canvas.height !== Math.round(height * ratio)
  ) {
    canvas.width = Math.round(width * ratio);
    canvas.height = Math.round(height * ratio);
  }
  const context = canvas.getContext("2d");
  context.setTransform(ratio, 0, 0, ratio, 0, 0);
  context.clearRect(0, 0, width, height);
  const margin = { top: 20, right: 18, bottom: 26, left: 48 };
  const plotWidth = width - margin.left - margin.right;
  const plotHeight = height - margin.top - margin.bottom;
  const values = rows.map((row) => Number(row[key])).filter(Number.isFinite);
  if (!values.length) {
    context.fillStyle = "#656d79";
    context.font = "10px ui-monospace, monospace";
    context.fillText("WAITING FOR WORKER ACTIONS", margin.left, height / 2);
    return;
  }
  let min = Math.min(...values);
  let max = Math.max(...values);
  const padding = (max - min || Math.abs(max) || 1) * 0.12;
  min -= padding;
  max += padding;
  context.strokeStyle = "#1c1f25";
  context.fillStyle = "#6e7580";
  context.font = "9px ui-monospace, monospace";
  context.lineWidth = 1;
  for (let index = 0; index <= 4; index += 1) {
    const y = margin.top + (plotHeight * index) / 4;
    context.beginPath();
    context.moveTo(margin.left, y);
    context.lineTo(width - margin.right, y);
    context.stroke();
    const value = max - ((max - min) * index) / 4;
    context.fillText(format(value, Math.abs(value) < 1 ? 3 : 1), 6, y + 3);
  }
  const visible =
    mode === "recorded" ? rows.slice(0, cursor + 1) : rows.slice();
  const denominator = Math.max(1, rows.length - 1);
  context.strokeStyle = fields[key].color;
  context.lineWidth = 1.75;
  context.beginPath();
  visible.forEach((row, index) => {
    const x = margin.left + (plotWidth * (row.step - 1)) / denominator;
    const y =
      margin.top + plotHeight - (plotHeight * (row[key] - min)) / (max - min);
    if (index === 0) context.moveTo(x, y);
    else context.lineTo(x, y);
  });
  context.stroke();
  const current = visible.at(-1);
  const x = margin.left + (plotWidth * (current.step - 1)) / denominator;
  const y =
    margin.top + plotHeight - (plotHeight * (current[key] - min)) / (max - min);
  context.fillStyle = fields[key].color;
  context.beginPath();
  context.arc(x, y, 3.5, 0, Math.PI * 2);
  context.fill();
  context.fillStyle = "#626975";
  context.fillText("1", margin.left, height - 7);
  context.fillText(String(rows.length), width - margin.right - 17, height - 7);
}

function render() {
  labels();
  if (mode === "waiting") {
    elements.step.textContent = "000 / 090";
    elements.reward.textContent = "—";
    elements.loss.textContent = "—";
    elements.kl.textContent = "—";
    elements.length.textContent = "—";
    elements.state.textContent = "Waiting for Arena";
  } else if (mode === "live") {
    const point = rows.at(-1);
    elements.step.textContent = `${String(live.cursor + 1).padStart(3, "0")} / ${String(live.totalActions).padStart(3, "0")}`;
    elements.reward.textContent = format(point?.reward, 2);
    elements.loss.textContent = format(live.current?.reward, 2);
    elements.kl.textContent = `${format(point?.kl, 1)}%`;
    elements.length.textContent = format(point?.mean_length, 0);
    elements.position.max = String(Math.max(0, live.totalActions - 1));
    elements.position.value = String(Math.max(0, live.cursor));
    elements.state.textContent = `Live · T${String(live.tick).padStart(2, "0")} · ${live.current?.agent || "ready"}`;
  } else {
    const row = rows[cursor];
    elements.step.textContent = `${String(row.step).padStart(3, "0")} / ${rows.length}`;
    elements.reward.textContent = format(row.reward, 3);
    elements.loss.textContent = format(row.loss, 5);
    elements.kl.textContent = format(row.kl, 3);
    elements.length.textContent = format(row.mean_length, 1);
    elements.position.max = String(rows.length - 1);
    elements.position.value = String(cursor);
    elements.play.textContent = playing
      ? "Pause"
      : cursor === rows.length - 1
        ? "Replay"
        : "Play";
    elements.state.textContent =
      cursor === rows.length - 1
        ? "Recorded run complete"
        : playing
          ? "Replaying recorded run"
          : "Recorded replay paused";
  }
  elements.state.parentElement.classList.toggle(
    "done",
    mode === "recorded" && cursor === rows.length - 1,
  );
  document
    .querySelectorAll("canvas[data-chart]")
    .forEach((canvas) => chart(canvas, canvas.dataset.chart));
}

function frame(now) {
  const elapsed = Math.min(250, now - lastFrame);
  lastFrame = now;
  if (mode === "recorded" && playing) {
    accumulator += elapsed * Number(elements.speed.value);
    while (accumulator >= 120 && playing) {
      accumulator -= 120;
      if (cursor < rows.length - 1) cursor += 1;
      else playing = false;
      render();
    }
  }
  requestAnimationFrame(frame);
}

function allowedSyncUrl(value) {
  try {
    const url = new URL(value);
    return (
      url.pathname.startsWith("/api/replay-sync/") &&
      ((url.protocol === "https:" &&
        url.hostname.endsWith(".us.sb.tenki.sh")) ||
        ((url.hostname === "127.0.0.1" || url.hostname === "localhost") &&
          ["http:", "https:"].includes(url.protocol)))
    );
  } catch {
    return false;
  }
}

function finite(value, fallback = 0) {
  return Number.isFinite(Number(value)) ? Number(value) : fallback;
}

function applyArenaState(data) {
  if (data?.type !== "sentry-loop-arena-sync" || data.version !== 1) return;
  rows = Array.isArray(data.points)
    ? data.points.slice(0, 1000).map((point, index) => ({
        step: index + 1,
        reward: finite(point.reward),
        loss: finite(point.loss),
        kl: finite(point.kl),
        mean_length: finite(point.mean_length),
      }))
    : [];
  live = {
    seed: Math.max(0, Math.floor(finite(data.seed))),
    policy: String(data.policy || "baseline").slice(0, 24),
    cursor: Math.max(-1, Math.floor(finite(data.cursor, -1))),
    totalActions: Math.max(
      1,
      Math.min(1000, Math.floor(finite(data.totalActions, 90))),
    ),
    tick: Math.max(0, Math.floor(finite(data.tick))),
    current: data.current
      ? {
          agent: String(data.current.agent || "ready").slice(0, 24),
          action: String(data.current.action || "waiting").slice(0, 80),
          status: String(data.current.status || "ready").slice(0, 40),
          reward: finite(data.current.reward),
        }
      : null,
  };
  mode = "live";
  playing = false;
  render();
}

async function pollArena() {
  if (!syncRequested) return;
  try {
    const response = await fetch(syncUrl, { cache: "no-store" });
    if (response.ok) applyArenaState(await response.json());
  } catch {
    /* The next poll recovers after a transient deploy or network interruption. */
  } finally {
    setTimeout(pollArena, document.hidden ? 1800 : 450);
  }
}

elements.play.addEventListener("click", () => {
  if (mode !== "recorded") return;
  if (cursor === rows.length - 1) cursor = 0;
  playing = !playing;
  accumulator = 0;
  render();
});
elements.restart.addEventListener("click", () => {
  if (mode !== "recorded") return;
  cursor = 0;
  playing = true;
  accumulator = 0;
  render();
});
elements.position.addEventListener("input", () => {
  if (mode !== "recorded") return;
  cursor = Number(elements.position.value);
  playing = false;
  accumulator = 0;
  render();
});
addEventListener("resize", render);

render();
void pollArena();
requestAnimationFrame(frame);
